server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:~/blooddonorsdb;DB_CLOSE_ON_EXIT=FALSE
    username: rest
    password: rest
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
